apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: debug
    image: open5gs-decrypted:latest
    command: ["/bin/sh"]
    imagePullPolicy: Never
    stdin: true
    tty: true
  restartPolicy: Never
