apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: open5gs-nrf-net
  namespace: open5gs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-open5gs",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "172.22.0.12/24",
          "gateway": "172.22.0.1"
        }
      ]
    }
  }'
