apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf
  namespace: open5gs
spec:
  selector:
    app: open5gs-ausf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777         # Service port (accessible from other pods)
      targetPort: 7777   # Port on the container
  type: ClusterIP         # Or use NodePort/LoadBalancer if needed
