apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: open5gs
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - name: mongo-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    - name: mongo-udp
      port: 27017
      protocol: UDP
      targetPort: 27017
