apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf
  namespace: open5gs
  labels:
    app: smf
spec:
  type: ClusterIP
  selector:
    app: smf
  ports:
    - name: diameter-tcp
      protocol: TCP
      port: 3868
      targetPort: 3868

    - name: diameter-sctp
      protocol: SCTP
      port: 3868
      targetPort: 3868

    - name: smf-extra-tcp
      protocol: TCP
      port: 5868
      targetPort: 5868

    - name: smf-extra-sctp
      protocol: SCTP
      port: 5868
      targetPort: 5868

    - name: pfcp
      protocol: UDP
      port: 8805
      targetPort: 8805

    - name: gtp-c
      protocol: UDP
      port: 2123
      targetPort: 2123

    - name: smf-api
      protocol: TCP
      port: 7777
      targetPort: 7777

    - name: smf-metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
