apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: open5gs
data:

  MCC: "001"
  MNC: "01"
  MAX_NUM_UE: "1024"

  udm.yaml: |
    logger:
      file:
        path: /open5gs/install/var/log/open5gs/udm.log

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    global:
      max:
        ue: MAX_NUM_UE

    udm:
      hnet:
        - id: 1
          scheme: 1
          key: /open5gs/install/etc/open5gs/hnet/curve25519-1.key
        - id: 2
          scheme: 2
          key: /open5gs/install/etc/open5gs/hnet/secp256r1-2.key
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          scp:
            - uri: http://open5gs-scp:7777
