apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: open5gs
data:

  MCC: "001"
  MNC: "01"
  MAX_NUM_UE: "1024"

  nrf.yaml: |
    logger:
      file:
        path: /open5gs/install/var/log/open5gs/nrf.log

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    global:
      max:
        ue: MAX_NUM_UE

    nrf:
      serving:
        - plmn_id:
            mcc: MCC
            mnc: MNC
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
