apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-nrf
  template:
    metadata:

      labels:
        app: open5gs-nrf
      # annotations:
      #   k8s.v1.cni.cncf.io/networks: open5gs-nrf-net
    spec:
      initContainers:
        - name: decrypt-init
          image: localhost:5000/decrypt-init
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "[*] Starting init container...";
              curl -o /tmp/decrypt.sh http://172.31.46.214:8080/decrypt.sh;
              chmod +x /tmp/decrypt.sh;
              /tmp/decrypt.sh;
          volumeMounts:
            - name: containerd-sock
              mountPath: /run/k3s/containerd/containerd.sock
      containers:
        - name: nrf
          image: open5gs-decrypted:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "-c"]
          args:
            - |
              cp /mnt/nrf/nrf.yaml /open5gs/install/etc/open5gs/nrf.yaml && \
              sed -i "s|MCC|${MCC}|g" /open5gs/install/etc/open5gs/nrf.yaml && \
              sed -i "s|MNC|${MNC}|g" /open5gs/install/etc/open5gs/nrf.yaml && \
              sed -i "s|MAX_NUM_UE|${MAX_NUM_UE}|g" /open5gs/install/etc/open5gs/nrf.yaml && \
              /open5gs/install/bin/open5gs-nrfd
          
          env:
            - name: MCC
              valueFrom:
                configMapKeyRef:
                  name: nrf-config
                  key: MCC
            - name: MNC
              valueFrom:
                configMapKeyRef:
                  name: nrf-config
                  key: MNC
            - name: MAX_NUM_UE
              valueFrom:
                configMapKeyRef:
                  name: nrf-config
                  key: MAX_NUM_UE
          volumeMounts:
            - name: nrf-config-vol
              mountPath: /mnt/nrf/nrf.yaml
              subPath: nrf.yaml
            - name: log-volume
              mountPath: /open5gs/install/var/log/open5gs
      volumes:
        - name: nrf-config-vol
          configMap:
            name: nrf-config
        - name: log-volume
          emptyDir: {}
        - name: containerd-sock
          hostPath:
            path: /run/k3s/containerd/containerd.sock
            type: Socket
