apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-config
  namespace: open5gs
data:
  MCC: "001"
  MNC: "01"
  MAX_NUM_UE: "1024"
  TAC: "1"

  amf.yaml: |
    logger:
      file:
        path: /open5gs/install/var/log/open5gs/amf.log

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    global:
      max:
        ue: MAX_NUM_UE

    amf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          scp:
            - uri: http://open5gs-scp:7777

      ngap:
        server:
          - address: 0.0.0.0

      guami:
        - plmn_id:
            mcc: MCC
            mnc: MNC
          amf_id:
            region: 2
            set: 1

      tai:
        - plmn_id:
            mcc: MCC
            mnc: MNC
          tac: TAC

      plmn_support:
        - plmn_id:
            mcc: MCC
            mnc: MNC
          s_nssai:
            - sst: 1

      security:
        integrity_order: [ NIA2, NIA1, NIA0 ]
        ciphering_order: [ NEA0, NEA1, NEA2 ]

      network_name:
        full: Open5GS

      amf_name: open5gs-amf

      metrics:
        server:
          - address: 0.0.0.0
            port: 9091

      time:
        t3512:
          value: 540
