apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  namespace: open5gs
spec:
  selector:
    app: open5gs-amf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777         # Service port (accessible from other pods)
      targetPort: 7777   # Port on the container
    - name: ngap
      protocol: SCTP
      port: 38412        # NGAP port (accessible from other pods)
      targetPort: 38412  # Port on the container
    - name: metrics
      protocol: TCP
      port: 9091         # Metrics port (accessible from other pods)
      targetPort: 9091   # Port on the container
  type: ClusterIP         # Or use NodePort/LoadBalancer if needed
