apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nssf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-nssf
  template:
    metadata:
      labels:
        app: open5gs-nssf
      # annotations:
      #   k8s.v1.cni.cncf.io/networks: open5gs-nrf-net
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo 27017; do echo waiting for mongo; sleep 2; done;']
        - name: wait-for-nrf
          image: busybox
          command: ['sh', '-c', 'until nc -z open5gs-nrf 7777; do echo waiting for nrf; sleep 2; done;']
        - name: wait-for-scp
          image: busybox
          command: ['sh', '-c', 'until nc -z open5gs-scp 7777; do echo waiting for scp; sleep 2; done;']


      containers:
        - name: nssf
          image: open5gs-decrypted:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "-c"]
          args:
            - |
              cp /mnt/nssf/nssf.yaml /open5gs/install/etc/open5gs/nssf.yaml && \
              sed -i "s|MAX_NUM_UE|${MAX_NUM_UE}|g" /open5gs/install/etc/open5gs/nssf.yaml && \
              /open5gs/install/bin/open5gs-nssfd
          env:
            - name: MCC
              valueFrom:
                configMapKeyRef:
                  name: nssf-config
                  key: MCC
            - name: MNC
              valueFrom:
                configMapKeyRef:
                  name: nssf-config
                  key: MNC
            - name: MAX_NUM_UE
              valueFrom:
                configMapKeyRef:
                  name: nssf-config
                  key: MAX_NUM_UE
          
          volumeMounts:
            - name: nssf-config-vol
              mountPath: /mnt/nssf/nssf.yaml
              subPath: nssf.yaml
            - name: log-volume
              mountPath: /open5gs/install/var/log/open5gs

      volumes:
        - name: nssf-config-vol
          configMap:
            name: nssf-config
        - name: log-volume
          emptyDir: {}
