apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: open5gs
spec:
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: NodePort  # or ClusterIP / LoadBalancer based on setup
